apiVersion: apps/v1
kind: Deployment
metadata:
  name: depositserver
spec:
  selector:
    matchLabels:
      app: depositserver
  replicas: 1
  template:
    metadata:
      labels:
        app: depositserver
    spec:
      containers:
        - name: depositserver
          image: hoceto/depositserver:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8093
            name: depositserver