apiVersion: v1
kind: Service
metadata:
  name: gateway-communication
spec:
  type: LoadBalancer
  ports:
    - port: 8095
      protocol: TCP
      targetPort: 8095      
  selector:
    app: gatewayserver