apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec:
  type: ClusterIP
  ports:
    - port: 8085
  selector:
    app: gatewayserver
---

apiVersion: v1
kind: Service
metadata:
  name: userserver
spec:
  type: ClusterIP
  ports:
    - port: 8090  
  selector:
    app: userserver
---

apiVersion: v1
kind: Service
metadata:
  name: workerserver
spec:
  type: ClusterIP
  ports:
    - port: 8091
  selector:
    app: workerserver
---

apiVersion: v1
kind: Service
metadata:
  name: depositserver
spec:
  type: ClusterIP
  ports:
    - port: 8093
  selector:
    app: depositserver
---

apiVersion: v1
kind: Service
metadata:
  name: cardserver
spec:
  type: ClusterIP
  ports:
    - port: 8094
  selector:
    app: cardserver